### ISSUE TITLE
Maybe alert feature is needed

### ISSUE THREAD

**Issue by keanesnow98** [TomokiMiyauci/me#266]
Hello, I have visited your page and opened one of your blog and I like it.
So, I left my commend somewhere or rather it was a question and then soon I left the page.
When I came back, I wanted to check if there were any replies, but I couldn't find my own comment.

So, I was thinking, it would be great if there is an alert button which gives me reply notification.
I don't know how you built your db, but you can add some fields to comments and query them to search unread replies.

Another solution can be saving blog posts for me, but I think it will affect the entire structure of your project.

PS: I think you haven't handled CORS in your backend properly since I got errors in frontend.

Thanks!

**Comment by TomokiMiyauci** [comment]
@keanesnow98 Thank you for your report.

This blog uses a 3rd party commenting system([utterances](https://utteranc.es/)). This is just embedded as an iframe, so the error may be in their system or the spec may have changed.

We are planning a complete replacement of this blog in the near future.
Perhaps the commenting system will be redesigned as well, so we hope you can wait for that.
